### ISSUE TITLE
Reivew linear algebra implementation

### ISSUE THREAD

**Issue by gravesti** [igrave/glmBfp#6]
Could we avoid calling the fortran and use Rcpp / Armadillo functions

https://github.com/RcppCore/RcppArmadillo/blob/f613cdba31d9b988832d71f648e7baa023f5b657/inst/include/armadillo_bits/translate_superlu.hpp#L143

https://gallery.rcpp.org/articles/simulation-smoother-using-rcpparmadillo/

**Comment by igrave** [comment]
Won't fix for now. To be reviewed in future
